name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: golang-crud-rest-api-ans-image
  DOCKERHUB_USERNAME: shivrajyadav
  DOCKERHUB_TOKEN: dckr_pat_eHl175cWM-CcqdsnFUSkfZNH9Vw

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          builder: ${{ env.BUILDKIT_BUILDER }}
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
